### ISSUE TITLE
Cannot execute() a prepared statement more than once

### ISSUE THREAD

**Issue by yktoo** [lexicalunit/nanodbc#29]
At first glance this is similar to #24, but in my case I'm not selecting but issuing DML statements.

The code is something like:
```c++
stmt.prepare(connection, "delete from ABC where key=?");

// some other stuff

void func(int key){
  stmt.bind(0, &key);
  stmt.execute();
}
```

So in the example above the first execution of `func()` succeeds, whereas any subsequent one fails at the `bind()` call. Digging deeper showed `prepare_bind()` is failing the call to `SQLDescribeParam`, which returns the `HY010 - Function sequence error` code.

At the same time, changing the code to
```c++
void func(int key){
  stmt.prepare(connection, "delete from ABC where key=?");
  stmt.bind(0, &key);
  stmt.execute();
  stmt.close();
}
```

eliminates the error, but then of we lose all the benefit of doing statement parsing only once.

The DB is Oracle, just in case that matters.

**Comment by weitjong** [comment]
I have exactly the opposite problem. After connecting to a database, all the initial DML statements of type ```create table ...``` always returning ```[iODBC][Driver Manager]Function sequence error```. I am using ```nanodbc::execute()``` method. Only after a first successful execution of DML statement of type ```insert table ...``` then the subsequent execution of ```create table ...``` would be successful.

Replacing the call with ```nanodbc::just_execute()``` solves the problem, however, this is not a solution because the app may not know in advance whether the SQL statement is DML or not.

The exception was thrown by ```columns()``` called by ```auto_bind()```. But why it only throws exception initially and not after a first successful execution of insert statement? The insert statement can be inserted to any existing tables and probably other DML statement type that I haven't tried may have the same side effect to cure this initial problem.

I am using a SQLite-ODBC driver compiled directly from source and installed to iODBC driver manager on a Linux host system. At this moment, I have no idea whether this is a driver-specific bug or something to do with nanodbc.

Thanks in advance for any help and thanks for providing such a great library.

**Comment by weitjong** [comment]
Sorry for the noise, I can confirm that my issue above is due a sqliteodbc driver bug when it was built against ```iODBC``` driver manager. Some how this issue does not come up again after I rebuilt the driver against ```unixODBC``` driver manager this time. Again, sorry for the noise.

**Comment by lexicalunit** [comment]
@weitjong Don't worry about it! This is good information to have here because it may help someone else in the future :)

**Comment by lexicalunit** [comment]
@yktoo I have been looking at this, I just haven't made comments here to that effect. I'm not seeing a super easy way to resolve this issue. The problem is that nanodbc ultimately translates into straight C API calls, and the order of those calls is important and also, sadly, particularly strict.

We could make this case work by automatically re-preparing the statement after execution because ODBC (I am pretty sure but correct me if I'm wrong) requires that to have happened to be able to call binding statements without error. However we don't want to make it so nanodbc makes those prepare statements unless the user wants them because that could easily lead to inefficient code paths.

A more elegant solution for your use case might be to encapsulate the data `"delete from ABC where key=?"` somehow, for example via a functor or lambda or other means (I just depends which would be best for you...).

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#56
