### ISSUE TITLE
Binding output parameter

### ISSUE THREAD

**Issue by jgarneau** [lexicalunit/nanodbc#31]
Hi,

   I'm trying to bind an output parameter with this code snippet :
      int id =0;
      nanodbc::statement statement(m_dbConn);
      prepare(statement, "CALL test(?);");
      statement.bind(0, &id, nanodbc::statement::PARAM_OUT);
      nanodbc::result results;
      results = execute(statement);

and the result is :
..\externals\nanodbc\include\nanodbc.cpp:1127: [MySQL][ODBC 5.3(a) Driver][mysqld-5.5.36]OUT or INOUT argument 1 for routine sabl.test is not a variable or NEW pseudo-variable in BEFORE trigger

What is the problem?

Here my MySQL procedure:
CREATE PROCEDURE `test` (OUT id INT)
BEGIN
	SET id = 5;
END

Thank You!

**Comment by thebyohazard** [comment]
I'm using MSSQL Server Express and I also have an exception of some kind when trying to bind an output parameter, so I don't think this is MySQL specific.
```c++
int main(int argc, char* argv[]){
    try {
        nanodbc::connection connection("DSN=SQLSERVER;UID=user;PWD=password;");
        nanodbc::statement statement(connection);
        prepare(statement,"CALL test(?);");
        int outParam;
        statement.bind(0,&outParam,nanodbc::statement::PARAM_OUT);
        //statement2.execute();
        cout << "param: " << outParam << endl;
        return 0;
    }
    catch(const nanodbc::database_error& e) {
        cerr << "ERROR: " << e.what() << endl;
        return 1;
    }
}
```
`ERROR: /home/user/Downloads/nanodbc-1.0.0/src/nanodbc.cpp:1269: [Microsoft][SQL Server Native Client 11.`

Something strange is going on with my error message so that it only prints part of the message, though, so I can't see what's exactly going wrong.

The actual driver is Microsoft's unixODBC driver: SQL Server Native Client 11.0

I don't know what version of nanodbc was in use at the time of this post, but I can't yet use c++11, so I'm on version 1.0.0.

@lexicalunit : this looks like your problem, perhaps? http://stackoverflow.com/questions/10318463/unixodbc-driver-manager-cannot-open-specified-library-on-install The accepted answer suggests a mismatch of architectures between unixODBC and the driver.

**Comment by thebyohazard** [comment]
The problem is that ODBC syntax for calling a stored procedure needs { curly brackets }
[MSDN reference on calling a stored procedure](https://technet.microsoft.com/en-us/library/aa198007%28v=sql.80%29.aspx)
Changing the line 
`prepare(statement,"CALL test(?);");`
to 
`prepare(statement,"{CALL test(?)};");`
fixed my error. 
Thanks for the great wrapper!

**Comment by lexicalunit** [comment]
Hahaha so that's it! You rock! :+1: 

@jgarneau Can you try out the brace syntax and see if that fixes things for you too?

**Comment by jgarneau** [comment]
Thank you very much, I will try that the next or two weeks.

De : thebyohazard [mailto:notifications@github.com]
Envoyé : 29 mai 2015 12:27
À : lexicalunit/nanodbc
Cc : Jean-Yves Garneau
Objet : Re: [nanodbc] Binding output parameter (#31)


The problem is that ODBC syntax for calling a stored procedure needs { curly brackets }
MSDN reference on calling a stored procedure<https://technet.microsoft.com/en-us/library/aa198007%28v=sql.80%29.aspx>
Changing the line
prepare(statement,"CALL test(?);");
to
prepare(statement,"{CALL test(?)};");
fixed my error.
Thanks for the great wrapper!

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#58
